name: malstroem
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - cyarray
  - future
  - gdal
  - numpy
  - pip
  - python=3.7
  - ipython
  - scipy
  - flask
  - pip:
    - click-log==0.1.8
